// external components
import type { Metadata } from "next";
import { notFound } from 'next/navigation';
import { Locale } from "@/modules/gql/graphql";
import { Nunito_Sans } from "next/font/google";

// style sheets
import "./globals.css";
import SmoothScrolling from "@/components/utils/smoothScroll";

// local components
import Head from './head'
import i18nConfig from '../../i18nConfig'
import getNavData from "@/modules/fetchData/getNavData";
import Menu from '@/components/utils/navbar'

export const metadata: Metadata = {
    title: "Catherine Zhou",
    description: "Generated by create next app",
};

const nunito = Nunito_Sans({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-nunito",
    display: "swap",
    fallback: ["sans-serif"],
    adjustFontFallback: false,
});

export default async function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: "en" | "zh" };
}>) {
    if (!i18nConfig.locales.includes(locale)) {
        notFound();
    }

    const supportedLocales: Locale[] = [Locale.En, Locale.Zh];
    const lang = supportedLocales.includes(locale as Locale)
        ? (locale as Locale)
        : Locale.En;

    const navData = await getNavData(lang);
    return (
        <html lang={locale}>
            <Head />
            <body suppressHydrationWarning className={nunito.variable}>
                <SmoothScrolling>
                    <Menu data={navData.navData} locale={locale} />
                    {children}
                    {/* <Footer /> */}
                </SmoothScrolling>
            </body>
        </html>
    );
}