// external components
import type { Metadata } from "next";
import { notFound } from 'next/navigation';

// style sheets
import "./globals.css";

// local components
import Head from './head'
import i18nConfig from '../../i18nConfig'

export const metadata: Metadata = {
    title: "Catherine Zhou",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: "en" | "zh" };
}>) {
    if (!i18nConfig.locales.includes(locale)) {
        notFound();
    }

    return (
        <html lang={locale}>
            <Head />
            <body suppressHydrationWarning>
                {children}
            </body>
        </html>
    );
}